### ISSUE TITLE
Brand identity guidelines

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#17]
Jonty has approached designer of original H logo

**Comment by syberphunk** [comment]
related: https://forum.hackspace.org.uk/t/new-hackspace-foundation-branding/32/1

**Comment by idnorton** [comment]
I'm not sure that we have enough of a brand identity for this to be considered "In progress" so I'm demoting it back to the backlog.

If either @syberphunk or @Jonty disagree, please feel free to move it back.

**Comment by proffalken** [comment]
@Jonty / @idnorton / @syberphunk - the last update on the forum was nearly 3 years ago.

Is it safe to assume that the new logo was not created or have I missed another thread somewhere?

https://forum.hackspace.org.uk/t/new-hackspace-foundation-branding/32/55

**Comment by syberphunk** [comment]
@proffalken Indeed it did not happen, and no-one has otherwise complained about the existing logo, so I'd deem it suitable for now at least.

**Comment by proffalken** [comment]
ok, thanks @syberphunk, in that case I'm going to suggest closing this ticket off and we can revisit/re-open as needed in future.

I'll give it until 5pm Friday 29th September, and unless anyone else says anything, I'll close it.

**Comment by proffalken** [comment]
No further comments added, closing.
