### ISSUE TITLE
Gather contact details (email) for hackspaces ready for surveys and membership drive

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#19]

**Comment by syberphunk** [comment]
Related: https://forum.hackspace.org.uk/t/how-are-we-going-to-do-the-initial-outreach-to-all-the-new-spaces/35/2

**Comment by Axford** [comment]
have finished going through all the hackspaces with missing email accounts (at least the active and starting ones), filled in as many blanks as possible.  38 usable addresses (across 66 hackspaces)

**Comment by Axford** [comment]
Fligg is going to try and make direct contact with the "gaps" to chase down a contact email

**Comment by BuildTheRobots** [comment]
Currently in communication with a few of the gaps.

Following has NOT been sent out, but I want to save it as a "snippet" for future refining....
"Step one is getting details for the current spaces around the UK, hence me contacting you. if you don't mind I'll be back in contact later for step 2 - trying to work out what groups are currently doing ;) We've decided to try and do this directly with the trustees/directors in part to avoid excessive bikeshedding, but also, to avoid asking people to say things in public unnecessarily (for example we might not have had quite as much insurance as we could have done for a little while...). "

**Comment by BuildTheRobots** [comment]
general email going out is as follows:

Hi [Name || XXX Hackspace!]]

EITHER:
Hope everyone is well up your way.
I hope you don't mind me contacting you directly, but your details were on [Facebook|thing].

I'm Fligg, one of the directors from Leeds Hackspace - if you've been to events like EMFcamp then you might have noticed me wombling around in pink high viz or playing with arcade machines.

I and a few other Hackspace organisers are trying to collate some details for Hackspaces around the UK, specifically the ability to contact the directors/trustees directly.

It's nothing sinister; we're trying to collate some information together about how Hackspaces currently work and how we can make it easier for new Hackspaces in the future (think door locks, access control, insurance, articles of association, codes of conduct etc...). We're starting by trying to contact trustees directly to avoid excessive bikeshedding and step one is obviously confirming contact details.

If you have a directors/trustees/chairperson email address that you're willing to give out, we'll promise not to spam or publish it, but we will be in contact in the next couple of months with a couple more questions.

Greatest of thanks,

Fligg
Leeds HackSpace

**Comment by amunizp** [comment]
I am guessing it is OK to invite other hackerspace leads to the forum and this github group.

**Comment by Jonty** [comment]
@amunizp Please do not, we do not have everything in place for initial communication yet.

**Comment by amunizp** [comment]
OK, I had a chat with Stuart from Newbury who as a small group have discussed about the foundation. I gave him the link to discourse and github, but asked him not to join yet. As they are small they are very active and would benifit from the UK-hackspace.

**Comment by notquitehere** [comment]
I'll try to find some time this evening to sketch out our on boarding documentation so we can start inviting people again.

tamarisk

## 

p: 07949 151 100
e: tamarisk@tamarisk.it
t: @notquitehere

**Comment by idnorton** [comment]
Thanks @notquitehere please shout if you need help :)

**Comment by BuildTheRobots** [comment]
All hackspaces in the list have been contacted. Not all have replied as yet.

**Comment by syberphunk** [comment]
@BuildTheRobots could you note on the google sheet which you've had responses from?
@notquitehere how's the onboard documentation coming along?

**Comment by castaway** [comment]
As we got as far as sending a survey, I believe the initial push on this is done - responses/furture spaces can be added as/when they appear

**Comment by syberphunk** [comment]
However this failed to send to everyone, so should be resent.

**Comment by castaway** [comment]
@syberphunk yes, in progress.. and this is the wrong place for that note..
