### ISSUE TITLE
Write initial approach email

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#20]

**Comment by syberphunk** [comment]
Related: https://forum.hackspace.org.uk/t/how-are-we-going-to-do-the-initial-outreach-to-all-the-new-spaces/35/2

**Comment by amunizp** [comment]
I think Any email sent out would be great if it has links to definitions to terms like 'bikeshedding'. 
Related link goes to survey but there was a draft email somewhere.

**Comment by castaway** [comment]
@amunizp worth starting the @glossary@ doc now then? I don't think we have yet..

**Comment by amunizp** [comment]
Dunno, or commit ourselves to avoid the terms? if glossary doc, would it go under resources? yeah it would.

**Comment by castaway** [comment]
@amunizp Kay had volunteered to review things for clarity (its her job).. we should still have a doc imo

**Comment by notquitehere** [comment]
We can avoid such terms in our external communications however it's not realistic to expect people not to use such terms in less formal communications. For this reason we're making a glossary (which will be on the website).

tamarisk

## 

p: 07949 151 100
e: tamarisk@tamarisk.it
t: @notquitehere

**Comment by amunizp** [comment]
Started:
https://github.com/UKHackspaceFoundation/resources/blob/master/glossary.md

**Comment by idnorton** [comment]
There is an issue for writing a glossary which has been added to as terms
crop up.

See UKHackspaceFoundation/UKHackspaces.github.io#11

On 19 Nov 2016 23:09, "amp" notifications@github.com wrote:

Started:
https://github.com/UKHackspaceFoundation/resources/blob/master/glossary.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/UKHackspaceFoundation/foundation/issues/20#issuecomment-261746013,
or mute the thread

**Comment by idnorton** [comment]
I'm pretty sure that @BuildTheRobots has already done this, can you update please Fligg?

**Comment by BuildTheRobots** [comment]
Not started a glossary, or at least nothing that couldn't be replicated in
minutes - I hope that's actually what I'm being asked :)

As to not using certain terms with our external communication, this strikes
me as a slippery slope and I wonder where we draw the line? I seem to spend
an inordinate amount of time trying to explain what the concept of a
hackspace is, maybe we should be careful not to use this term either? ;)

**Comment by idnorton** [comment]
@BuildTheRobots No, glossary was a tangent to the original issue of initial approach email 😀

**Comment by Axford** [comment]
have drafted an initial comms email and supporting survey on Google Drive

**Comment by idnorton** [comment]
This has been sent so I think we can call it done unless we want to add lessons learned?

**Comment by castaway** [comment]
@idnorton Would suggest a new task for "follow up on initial approach email" ?
