### ISSUE TITLE
Develop an approach for fostering new spaces (council property, etc)

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#24]
use our existing contacts with councils, property owners, and government to actually foster starting new spaces in meanwhile space - short lived spaces lasting a year or so, constantly fluxing but with persistent community and good links between them

**Comment by amunizp** [comment]
This is done IMHO by meeting up with local existing community groups, residents associations and similar. Instead of meeting up in pubs.  Normally they have access to spaces for activities and interact with the council.

**Comment by proffalken** [comment]
Does this still need a ticket? Is it intended that UKHSF will reach-out to councils across the UK and ask if they want a hack/makerspace in their area?

**Comment by amunizp** [comment]
IIRC More like HSF will recommend people that are looking for a space to do certain things that have been proven successful in other locations.

**Comment by proffalken** [comment]
@amunizp thanks - any more light you can shed on this or links to previous discussions are welcome, I'd love to shape this into something that was actionable and had a clear intended outcome :)

**Comment by amunizp** [comment]
As discussed in telegram chat, WIP is here:

https://drive.google.com/drive/folders/17KRt0cLtUb9BL-SIZWdb4o-qwnWkosPU

I believe in particular we developed some pints in book of informality

https://docs.google.com/document/d/1b0oXoujZKchS90-0NdU14NdqUDQ3YwlqQhHqRhG_BTU/edit?usp=drivesdk

But the OP is broad in scope so one could say the whole HOM is is the answer.

**Comment by proffalken** [comment]
@amunizp I think I'm going to close this in favour of opening up smaller tickets in future if they're needed.

"Write the HOM in order to complete this ticket" feels far too vague to me.

Happy to discuss here or via Telegram DM, but will assume it's ok to close by 1700hrs on 3/10/23 unless I hear otherwise.

**Comment by amunizp** [comment]
I believe this can be closed as this particular part has been answered.
