### ISSUE TITLE
Review, and potentially re-invigorate, past projects to help connect/support spaces (e.g. SpaceAPI)

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#26]

**Comment by JasperWallace** [comment]
spaceapi is here:

http://spaceapi.net/

Other than encouraging people to use it I'm not sure what we can add to it.

**Comment by idnorton** [comment]
Some discussion is already happening and it looks like the Space API is being forked:

http://lists.hackerspaces.org/pipermail/discuss/2017-January/011302.html

**Comment by proffalken** [comment]
Latest update seems to be that SpaceAPI continued and SpaceDirectory (the fork) didn't really go anywhere.

https://github.com/SpaceApi/directory appears to be the canonical code and was updated 2 days ago, so there could be some promise in including it here.

**Comment by proffalken** [comment]
Updated "[The Book of informality](https://docs.google.com/document/d/1b0oXoujZKchS90-0NdU14NdqUDQ3YwlqQhHqRhG_BTU/edit)" with details on how to add a space to SpaceAPI/SpaceDIR

**Comment by proffalken** [comment]
Quick survey on Telegram suggests that SpaceFed and SpaceSAML are probably a step too far for most spaces, so I'm going to close this for now and we can come back to it if needed.
