### ISSUE TITLE
Collate existing info on hackspaces (name, location, size, status)

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#3]
https://drive.google.com/open?id=1A8qqvTRa_5y9emOQezCQzVeH1aRXGM9qz5AiGoTB06A

**Comment by syberphunk** [comment]
I think this may have reached its peak for now until we have people from the individual hackspaces onboard and updating us with information, for example, such as how many members. Contact e-mail addresses are being chased up separately.
