### ISSUE TITLE
Structure of Hackspace Foundation

### ISSUE THREAD

**Issue by syberphunk** [UKHackspaceFoundation/foundation#31]

**Comment by amunizp** [comment]
Should the idea of how the cites work be implemented? What is a quorum? can votes be delegated if there is time constraint? Should there be time constraint on votes?

**Comment by syberphunk** [comment]
@amunizp Please take discussion points like this to the discourse forum.

**Comment by idnorton** [comment]
New articles of association are up at:

https://github.com/UKHackspaceFoundation/constitution/blob/master/articles.pdf

There's a discussion of them at:

https://forum.hackspace.org.uk/t/articles-of-association/60

I think this is done pending review.

**Comment by russss** [comment]
This is finalised, at least for version 1. Further changes should probably go into the [issue tracker for the constitution repo](https://github.com/UKHackspaceFoundation/constitution).
