### ISSUE TITLE
Allow Discourse to be used as a Mailing List

### ISSUE THREAD

**Issue by syberphunk** [UKHackspaceFoundation/foundation#35]
Discourse requires a POP3 server setup so that people can reply to it via e-mail and behave like a traditional mailing list.

Currently there is a POP3 server setup, however some configuration has caused the forum/mailing list to be locked down and produce 403 error(s) and inability to login. Replying via e-mail also currently doesn't work.

https://forum.hackspace.org.uk/

**Comment by russss** [comment]
Just a temporary issue, I'm just adding firewalling and it's broken docker, as per usual.

**Comment by russss** [comment]
The login issues are now fixed, can you try an email reply now?

**Comment by castaway** [comment]
Login seems fine as does reply on the forum.. reply via email is bouncing, says @idnorton

**Comment by idnorton** [comment]
Bouncy bounce:

```
Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain forum.hackspace.org.uk [2a03:b0c0:1:d0::611:4001].

The error that the other server returned was:
550 5.1.1 <reply+5ca7ac28c27f4fd6cbc3a1f8809bd222@forum.hackspace.org.uk>: Recipient address rejected: User unknown in virtual alias table
```

**Comment by russss** [comment]
OK, try now.

**Comment by idnorton** [comment]
No immediate bounce so looks like it's gone through?

**Comment by idnorton** [comment]
Apparently 'Sir not appearing in this forum post' though that could be down to delay between delivery to the mailbox and collection by the POP3 client.

**Comment by russss** [comment]
Hmm, oddly I haven't seen that one delivered yet. Perhaps Google has delayed it as the previous one bounced?

**Comment by idnorton** [comment]
@russss Oh could be, be the sensible thing to do.

**Comment by russss** [comment]
It just came through, and was rejected because the post was too short :)

**Comment by idnorton** [comment]
I totally didn't hit reply and send that to mailer-daemon@googlemail.com.... nope...

_cough_

So here's a new error now from discourse:

```
We're sorry, but your email message to ["reply+5ca7ac28c27f4fd6cbc3a1f8809bd222@forum.hackspace.org.uk"] (titled Re: [UK HSF] [Discourse Help] Mailing list mode reply: CURRENTLY BORKEN) didn't work.

Reason:

Body is too short (minimum is 20 characters)
Body is invalid; try to be a little more descriptive

If you can correct the problem, please try again.
```

So looks like it's working now, have tried to post again now (with a number of errors posting to noreply@ which is a bit of an odd address for some of the messages to come from)

**Comment by idnorton** [comment]
And that last one has now appeared.

**Comment by russss** [comment]
Good lord it finally worked. I've just dropped the minimum post length down to 1 character, it was annoying me too.

**Comment by idnorton** [comment]
@russss :+1:
