### ISSUE TITLE
Put together a survey to send out to hackspaces for a membership drive

### ISSUE THREAD

**Issue by syberphunk** [UKHackspaceFoundation/foundation#36]
https://drive.google.com/open?id=1vnsFEFNxrakR-A1Yn_5gX4YmZFCdzLi5yJclli51zVE

Related ticket: https://github.com/UKHackspaceFoundation/foundation/issues/19

**Comment by BuildTheRobots** [comment]
I'm tempted to say all steps need to be +1 and step one is actually finalise current contact and space details - eg member numbers, current organisation details, legal structure, regular meetings... essentially flesh out and expand the current spreadsheet.

**Comment by idnorton** [comment]
A survey has been sent however there were some issues with that.

Could I politely ask for @notquitehere or @Axford to slap an update here with where we're at please? Thankyou :)

**Comment by Axford** [comment]
@notquitehere has resent the survey, this time via Sendinblue - hopefully this will fix the low distribution from the first attempt.  Give it couple of weeks for responses, then call it done.  Should be able to get the sign-up process completed in parallel

**Comment by idnorton** [comment]
We did this.
