### ISSUE TITLE
Hammer out Definition of a Hackspace

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#4]
https://github.com/UKHackspaceFoundation/foundation/blob/master/define.md

**Comment by syberphunk** [comment]
Semi related: https://forum.hackspace.org.uk/t/things-that-are-not-spaces-but-we-would-like-to-recognise-as-part-of-the-community/33/6

**Comment by syberphunk** [comment]
Related: https://forum.hackspace.org.uk/t/definition-and-status-of-hackspaces/

**Comment by castaway** [comment]
It looks like this one is done - if buggy we can add tasks to fix the bugs
