### ISSUE TITLE
Basic membership signup/management tools

### ISSUE THREAD

**Issue by castaway** [UKHackspaceFoundation/foundation#44]
In the spirit of getting stuff done - initial signup/membership request forms using google forms - see https://drive.google.com/open?id=1lwX6lsce-ZrjLgJiWbu0MtC2YUBNlt7ypnEdoYovHYg

**Comment by castaway** [comment]
https://drive.google.com/open?id=0BzwRVAuohHqCOFhYUzFRbTdtM1k

**Comment by Axford** [comment]
nice one...  if we make a decision on how to handle payments, then we should be ready to implement almost straight away

**Comment by idnorton** [comment]
Damian Axford, [12.04.17 13:18]
We have a decision on payment handling:  GoCardless

Damian Axford, [12.04.17 13:19]
We may change or add additional payment methods in the future, but for the foreseeable, we'll work with GoCardless

Damian Axford, [12.04.17 13:19]
@russs already setup an HSF GoCardless account back when bank account was setup, so we're almost ready to go with accepting payments

**Comment by Axford** [comment]
given fast progress on "the real thing" (see /website repo) - propose we close this issue....  @castaway ?

**Comment by castaway** [comment]
@Axford go for it ;)
