### ISSUE TITLE
Foundation Code of Conduct and Consequences of Bad Behaviour

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#5]
https://github.com/UKHackspaceFoundation/foundation/blob/master/codeOfConduct.md

**Comment by Axford** [comment]
Added draft badBehaviour.md to the repo - https://github.com/UKHackspaceFoundation/foundation/blob/master/badBehaviour.md

**Comment by russss** [comment]
Just had a quick look at this - I think the HSF code of conduct should probably only concentrate on online interactions (if we do run events we can adopt an expanded code for them). We should definitely create a recommended code of conduct for spaces as well though, but that's out of scope here.

With that in mind I've tried to pare it down a bit, and borrowed a bit from the [Django code of conduct](https://www.djangoproject.com/conduct/). I've combined the "consequences" stuff into the Code of Conduct document - that badBehaviour doc is good (is it Nottinghack's?) but more geared towards physical spaces I think.

[Work in progress here](https://github.com/UKHackspaceFoundation/foundation/blob/codeofconduct/codeOfConduct.md).

**Comment by Axford** [comment]
Fine by me, but fairly indifferent, as don't see an issue with having a single extended CoC that covers online and physical interactions.

Could move the extended Code of Conduct off to the /resources repo (along with consequences stuff), as an example for other spaces to use.... and based on hacman :)

**Comment by notquitehere** [comment]
Given that we are actually planning a meetup and for the sake of keeping things simple, I personally feel that a single code of conduct would be  preferable. Also you seem to have removed the guidance on how to report an issue.

I do also agree that we should have a sample CoC and grievance procedure in the hackspace manual :)

Also thank you. :)

tamarisk 

-- 

p: 07949 151 100
e: tamarisk@squashedfly.eu
t: @squashedfly_
w: http://squashedfly.eu

**Comment by amunizp** [comment]
Created CoC document in manual. On phone now but happy to populate it andvlater raise a separate issue to review. https://github.com/UKHackspaceFoundation/resources/blob/master/Hackspace%20Owners%20Manual/CoC.md @notquitehere

**Comment by idnorton** [comment]
@amunizp the empty file has been removed as it wasn't really in the right place, sorry :/

We have a CoC up at https://www.hackspace.org.uk/foundation/codeOfConduct.md now which is fed from the file in the foundation repo, that's a more appropriate place for it to live.

Did we reach a conclusion about the CoC being only for virtual? Should I post this discussion to Discourse so that we can get a consensus as I'm not sure we reached one here?

**Comment by idnorton** [comment]
Created a thread to discuss this over on the forum, I think that's the right approach.

See https://forum.hackspace.org.uk/t/hackspace-foundation-code-of-conduct/216

Once we have a decision on the approach (I'll give it a week for people to have their say) we'll draw a line under it and implement one way or the other.

**Comment by Axford** [comment]
Have added a footer to the main website which links to the CoC.  When we add a signup process, we can ensure the CoC features and is agreed to.

**Comment by idnorton** [comment]
We have a CoC published, we're at the point that improvements should be requested and this closed off.
