### ISSUE TITLE
Comms channels

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#8]
https://github.com/UKHackspaceFoundation/foundation/blob/master/comms.md

**Comment by Axford** [comment]
An umbrella task to make sure the overall set of comms channels is sufficient and logical.  There are related tasks for Email, Discourse, etc

**Comment by syberphunk** [comment]
Issue is vague and not a task or set of tasks someone can own or act on, so closing to be recreated or rephrased.
