### ISSUE TITLE
Email and Helpmonks

### ISSUE THREAD

**Issue by idnorton** [UKHackspaceFoundation/foundation#9]

**Comment by Axford** [comment]
Need to get a generic email wired up to Helpmonks.

See: https://forum.hackspace.org.uk/t/handling-incoming-hsf-communications/30/4

**Comment by Axford** [comment]
Helpmonks organisation created, and initial admins added (see thread above) - now need to get the mail server updated so contact@hackspace.org.uk is forwarded to helpmonks

For ref:
https://hackspacefoundation.helpmonks.com/

**Comment by russss** [comment]
It's already done as per https://forum.hackspace.org.uk/t/handling-incoming-hsf-communications/30/13?u=russ
